savannahghi/pro_health_360_daktari

.circleci/config.yml, install_flutter_ci.sh, release-notes.txt
=> feat: setup deployment to firebase app tester

lib/presentation/router/route_generator.dart, test/widget_tests/application/core/services/feed_content_callbacks_test.dart
=> test: feed content callbacks

lib/presentation/onboarding/practitioner_kyc/common/kyc_utils.dart, lib/presentation/router/route_generator.dart
=> chore: remove unused code in KYC utils

.circleci/config.yml, lib/application/core/services/helpers.dart, lib/application/core/services/init_app.dart, lib/application/redux/states/app_state.dart, lib/domain/core/value_objects/app_widget_keys.dart, lib/infrastructure/afyamoja_endpoint_context.dart, lib/infrastructure/endpoints.dart, lib/presentation/core/afya_moja_app.dart, pubspec.lock, pubspec.yaml, test/unit_tests/helpers_test.dart, test/unit_tests/infrastructure/endpoints_test.dart
- setup prod endpoints
- load endpoints based on the app setup data and environment
- strip out demo and E2E contexts in endpoints
=> fix: endpoint setup

.circleci/config.yml, .gitignore
=> feat: deploy to play store alpha track

.circleci/config.yml, lib/application/core/services/init_app.dart, lib/application/redux/actions/core/update_user_state_action.dart, lib/application/redux/actions/kyc_state_actions/individual_practitioner_kyc_action.dart, lib/application/redux/actions/kyc_state_actions/save_kyc_details_action.dart, lib/application/redux/states/practitioner_kyc_models/organization_details.dart, lib/domain/core/entities/kra_details.dart, lib/domain/core/entities/practice_service.dart, lib/infrastructure/repository/database_mobile.dart, lib/presentation/core/afya_moja_app.dart, lib/presentation/onboarding/practitioner_kyc/common/practitioner_kyc_state_view_model.dart, lib/presentation/onboarding/practitioner_kyc/common/widgets/director_identification_result_card.dart, lib/presentation/onboarding/practitioner_kyc/common/widgets/director_identifications.dart, lib/presentation/onboarding/practitioner_kyc/common/widgets/kyc_page_bottom_actions.dart, lib/presentation/onboarding/practitioner_kyc/common/widgets/kyc_page_header.dart, lib/presentation/onboarding/practitioner_kyc/common/widgets/kyc_scaffold.dart, lib/presentation/onboarding/practitioner_kyc/common/widgets/supporting_documents_result_card.dart, lib/presentation/onboarding/practitioner_kyc/individual/individual_practitioner_step_one.dart, lib/presentation/onboarding/practitioner_kyc/individual/individual_practitioner_step_two.dart, lib/presentation/onboarding/practitioner_kyc/individual/individual_practitioner_view_model.dart, pubspec.lock, pubspec.yaml, test/widget_tests/auth_manager_test.dart
- use appsetupdata object when initializing app
- load endpoints directly from the appsetupdata oject
- improve code formatting
=> fix: app fixes

.circleci/config.yml, lib/application/core/services/init_app.dart, lib/application/redux/actions/core/update_user_state_action.dart, lib/application/redux/actions/kyc_state_actions/individual_practitioner_kyc_action.dart, lib/application/redux/actions/kyc_state_actions/save_kyc_details_action.dart, lib/application/redux/states/practitioner_kyc_models/organization_details.dart, lib/domain/core/entities/kra_details.dart, lib/domain/core/entities/practice_service.dart, lib/infrastructure/repository/database_mobile.dart, lib/presentation/core/afya_moja_app.dart, lib/presentation/onboarding/practitioner_kyc/common/practitioner_kyc_state_view_model.dart, lib/presentation/onboarding/practitioner_kyc/common/widgets/director_identification_result_card.dart, lib/presentation/onboarding/practitioner_kyc/common/widgets/director_identifications.dart, lib/presentation/onboarding/practitioner_kyc/common/widgets/kyc_page_bottom_actions.dart, lib/presentation/onboarding/practitioner_kyc/common/widgets/kyc_page_header.dart, lib/presentation/onboarding/practitioner_kyc/common/widgets/kyc_scaffold.dart, lib/presentation/onboarding/practitioner_kyc/common/widgets/supporting_documents_result_card.dart, lib/presentation/onboarding/practitioner_kyc/individual/individual_practitioner_step_one.dart, lib/presentation/onboarding/practitioner_kyc/individual/individual_practitioner_step_two.dart, lib/presentation/onboarding/practitioner_kyc/individual/individual_practitioner_view_model.dart, pubspec.lock, pubspec.yaml, test/widget_tests/auth_manager_test.dart
- use appsetupdata object when initializing app
- load endpoints directly from the appsetupdata oject
- improve code formatting
=> fix: afya moja alpha release

lib/domain/core/value_objects/app_widget_keys.dart, lib/presentation/onboarding/common/afyamoja_landing_actions.dart, lib/presentation/onboarding/common/afyamoja_landing_page.dart, lib/presentation/onboarding/login/pages/afyamoja_phone_login_page.dart, lib/presentation/onboarding/login/widgets/afyamoja_phone_login.dart, lib/presentation/router/route_generator.dart, test/mocks/mocks.dart, test/widget_tests/auth_manager_test.dart, test/widget_tests/presentation/login/pages/afyamoja_phone_login_test.dart, test/widget_tests/presentation/onboarding/common/afyamoja_landing_actions_test.dart, test/widget_tests/presentation/onboarding/common/afyamoja_landing_page_test.dart
=> refactor: remove signup

lib/domain/core/entities/security_questions/security_question.dart, lib/domain/core/entities/security_questions/security_question.g.dart, lib/domain/core/entities/security_questions/security_question_response.dart, lib/domain/core/entities/security_questions/security_question_response.g.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/onboarding/security_questions/security_questions_page.dart, lib/presentation/router/route_generator.dart, lib/presentation/router/routes.dart, test/mocks/mocks.dart, test/unit_tests/domain/core/entities/security_questions/security_question_response_test.dart, test/unit_tests/domain/core/entities/security_questions/security_question_test.dart, test/unit_tests/presentation/onboarding/security_questions/security_questions_page_test.dart, test/unit_tests/presentation/router/route_generator_test.dart
=> chore: security questions page

lib/domain/core/value_objects/app_strings.dart, lib/domain/core/value_objects/app_widget_keys.dart, lib/presentation/onboarding/patient/add_new_patient_page.dart, lib/presentation/router/route_generator.dart, lib/presentation/router/routes.dart, test/unit_tests/presentation/onboarding/patient/add_new_patient_page_test.dart, test/unit_tests/presentation/router/route_generator_test.dart
=> feat: add new patient page

lib/application/core/services/helpers.dart, lib/application/redux/actions/core/phone_login_action.dart, lib/application/redux/actions/core/update_credentials_action.dart, lib/application/redux/actions/user_state_actions/refresh_token_action.dart, lib/infrastructure/repository/database_base.dart, lib/infrastructure/repository/database_mobile.dart, lib/infrastructure/repository/database_state_persistor.dart, lib/infrastructure/repository/migrations.dart, lib/presentation/core/auth_manager.dart, test/unit_tests/helpers_test.dart, test/unit_tests/infrastructure/repository/database_base_test.dart, test/unit_tests/infrastructure/repository/database_mobile_test.dart, test/widget_tests/application/core/services/helpers_test.dart
=> fix: credentials data persistence

lib/presentation/onboarding/login/widgets/login_widget.dart, test/widget_tests/presentation/login/pages/phone_login_test.dart
=> chore: remove forgot pin

lib/application/core/services/utils.dart, lib/presentation/engagement/home/pages/home_page.dart, lib/presentation/service_requests/pages/red_flags_page.dart, test/unit_tests/presentation/router/route_generator_test.dart, test/widget_tests/presentation/engagement/home/pages/home_page_test.dart, test/widget_tests/presentation/service_requests/service_requests_page_test.dart
=> chore: flag search and surveys temporarily

lib/application/core/services/utils.dart, lib/application/redux/actions/core/phone_login_action.dart, lib/application/redux/actions/core/update_staff_profile_action.dart, lib/application/redux/actions/update_user_profile_action.dart, lib/domain/core/entities/core/user.dart, lib/domain/core/entities/core/user.freezed.dart, lib/domain/core/entities/core/user.g.dart, lib/presentation/engagement/home/pages/home_page.dart, lib/presentation/engagement/home/widgets/appbar_user.dart, lib/presentation/profile/pages/user_profile_page.dart, lib/presentation/profile/widgets/user_details_card_widget.dart, test/mocks/mocks.dart, test/widget_tests/presentation/engagement/home/pages/home_page_test.dart, test/widget_tests/presentation/engagement/home/widgets/app_user_test.dart
=> chore: hook user logic to state

lib/domain/core/value_objects/app_strings.dart, lib/presentation/onboarding/set_nickname/set_nickname_page.dart
=> chore: set nickname visual hierachy

lib/application/redux/view_model_factories/app_entry_point_view_model_factory.dart, lib/application/redux/view_models/app_entry_point_view_model.dart, lib/presentation/core/afya_moja_app.dart, lib/presentation/core/auth_manager.dart, test/widget_tests/presentation/afya_moja_app_test.dart, test/widget_tests/presentation/auth_manager_test.dart
=> feat: refresh token

CHANGELOG.MD, CONTRIBUTING.md, README.md, android/app/src/main/AndroidManifest.xml, docs/app_versioning.MD, lib/application/core/services/init_app.dart, lib/application/redux/view_model_factories/app_entry_point_view_model_factory.dart, lib/domain/core/value_objects/app_name_constants.dart, lib/domain/core/value_objects/app_strings.dart, lib/infrastructure/repository/database_base.dart, lib/infrastructure/repository/database_mobile.dart, lib/infrastructure/repository/database_state_persistor.dart, lib/presentation/core/afya_moja_app.dart, pubspec.yaml, release-notes.txt, test/unit_tests/infrastructure/repository/database_base_test.dart, test/unit_tests/infrastructure/repository/database_mobile_test.dart, test/widget_tests/application/core/services/custom_client_test.dart, test/widget_tests/presentation/afya_moja_app_test.dart
- rename application from myCareHub to myCareHub Professional
- remove references to afyamoja
=> chore: rename application from afyamoja to MyCareHub Professional

lib/application/core/services/utils.dart
=> chore: remove appointments and surveys from profile

lib/domain/core/value_objects/app_strings.dart, lib/presentation/core/app_bar/custom_app_bar.dart, lib/presentation/onboarding/patient/add_new_patient_page.dart, lib/presentation/onboarding/patient/register_client_form_manager.dart, lib/presentation/onboarding/patient/widgets/facility_dropdown.dart, test/widget_tests/presentation/onboarding/patient/add_new_patient_page_test.dart
- Change patient registration ui
- Implement invite client checkbox
=> chore: change registration ui

lib/presentation/onboarding/verify_phone/widgets/verify_otp_widget.dart
- clear otp field when resend button is pressed
=> fix: clear otp field

lib/presentation/profile/pages/user_profile_page.dart, pubspec.lock, pubspec.yaml
=> feat: shared profile components

lib/presentation/onboarding/patient/register_client_form_manager.dart
- Fix null entry passed during register client api request
=> fix: null entry for api request

lib/application/core/services/utils.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/profile/pages/user_profile_page.dart, pubspec.lock, pubspec.yaml, test/widget_tests/presentation/profile/user_profile_page_test.dart
=> chore: user profile item update

lib/presentation/engagement/home/pages/home_page.dart, lib/presentation/engagement/home/widgets/action_card.dart, lib/presentation/service_requests/pages/red_flags_page.dart, lib/presentation/service_requests/pages/service_requests_page.dart, lib/presentation/service_requests/widgets/service_request_action_card.dart, test/widget_tests/presentation/engagement/home/pages/home_page_test.dart
=> chore: service requests positioning and removing TODOs

ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/demo.xcscheme, ios/Runner/AppDelegate.swift, ios/Runner/Info.plist
- fix handing when launching app
- update build number in info.plist file
=> feat: fix iOS build issues

lib/presentation/engagement/home/pages/home_page.dart, lib/presentation/onboarding/login/widgets/login_widget.dart, lib/presentation/service_requests/widgets/schedule_meet_dialog.dart, test/widget_tests/presentation/login/pages/phone_login_test.dart
=> chore: change width for large devices

lib/presentation/onboarding/patient/add_new_patient_page.dart, lib/presentation/onboarding/patient/date_picker.dart
=> fix: date field

ios/Flutter/demo.xcconfig, ios/Runner.xcodeproj/project.pbxproj, ios/Runner/Info.plist, lib/presentation/contact_admin/pages/contact_admin_page.dart, lib/presentation/contact_admin/widgets/contact_admin_card.dart
- fix broken contact admin buttons on ios
=> fix: fix broken contact admin buttons on ios

lib/domain/core/value_objects/app_strings.dart, lib/presentation/profile/faqs/pages/profile_faqs_page.dart, test/widget_tests/presentation/profile/FAQs/profile_faqs_page_test.dart
=> fix: profile FAQs

lib/application/core/services/utils.dart, lib/domain/core/value_objects/app_strings.dart, lib/domain/core/value_objects/app_widget_keys.dart, lib/presentation/create_group/invite_members/invite_members_page.dart, lib/presentation/create_group/invite_members/widgets/member_list_item.dart, lib/presentation/router/route_generator.dart, lib/presentation/router/routes.dart, test/unit_tests/presentation/router/route_generator_test.dart, test/widget_tests/presentation/create_group/invite_members_page_test.dart
=> feat: invite members

pubspec.lock, pubspec.yaml
- remove unused user_profile package
=> chore: remove unused user_profile package

pubspec.lock, pubspec.yaml
=> chore: fix wrapping country picker

.circleci/config.yml, .github/workflows/config.yaml, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner/Info.plist
- add stream api key to build configs
- fix ios config issues
=> fix: android and iOS deployment

lib/domain/core/value_objects/app_strings.dart, lib/presentation/communities/pages/community_list_page.dart, lib/presentation/core/bottom_nav/bottom_nav_items.dart, test/widget_tests/presentation/core/app_bar/custom_app_bar_test.dart
- rename communities to conversations
=> chore: rename communities to conversations

.circleci/config.yml, .github/workflows/config.yaml, README.md, lib/application/core/services/app_setup_data.dart, lib/application/core/services/helpers.dart, lib/application/core/services/init_app.dart, test/mocks/test_helpers.dart, test/unit_tests/app_setup_data_test.dart, test/unit_tests/helpers_test.dart
- move stream api key to AppSetupData
- apply the change to the deployment configuration
=> refactor: deployment configs

lib/presentation/communities/channel_page.dart, lib/presentation/communities/community_utils.dart
=> fix: add group name

lib/presentation/client_details/pages/client_health_page.dart, lib/presentation/communities/pages/community_list_page.dart, lib/presentation/contact_admin/pages/contact_admin_page.dart, lib/presentation/core/app_bar/app_bar_notification.dart, lib/presentation/create_group/create_group.dart, lib/presentation/create_group/invite_members/invite_members_page.dart, lib/presentation/engagement/home/pages/content_page.dart, lib/presentation/profile/faqs/pages/faq_detail_view_page.dart, lib/presentation/profile/faqs/pages/profile_faqs_page.dart, lib/presentation/profile/pages/settings_page.dart, lib/presentation/profile/pages/user_profile_page.dart, lib/presentation/surveys/pages/share_survey_page.dart, lib/presentation/surveys/pages/surveys_page.dart, test/widget_tests/presentation/core/app_bar/custom_app_bar_test.dart
- ensure notifications icon is always visible
- ensure appbar always has title
=> chore: fix app bar

lib/application/core/services/utils.dart, lib/domain/core/value_objects/app_strings.dart, lib/domain/core/value_objects/app_widget_keys.dart, lib/presentation/communities/channel_page.dart, lib/presentation/communities/pages/community_list_page.dart, lib/presentation/community/group_info/pages/group_info_page.dart, lib/presentation/community/group_info/widgets/group_member_item.dart, lib/presentation/community/group_info/widgets/member_list_actions_dialog.dart, lib/presentation/router/route_generator.dart, test/unit_tests/presentation/router/route_generator_test.dart, test/widget_tests/presentation/community/group_info_page_test.dart, test/widget_tests/presentation/community/member_list_actions_dialog_test.dart
=> chore: add group info page

lib/presentation/create_group/create_group.dart
=> fix: fix create group ui

lib/presentation/create_group/create_group.dart, lib/presentation/create_group/create_group_form_manager.dart
- Add labels to range slider
- Remove unused gender and client type value
s
=> fix: create group fixes

lib/domain/core/value_objects/app_strings.dart, lib/presentation/contact_admin/pages/contact_admin_page.dart, lib/presentation/onboarding/set_nickname/set_nickname_page.dart, lib/presentation/profile/faqs/pages/faq_detail_view_page.dart, lib/presentation/profile/faqs/pages/profile_faqs_page.dart, lib/presentation/profile/pages/edit_information_page.dart, lib/presentation/profile/pages/settings_page.dart, lib/presentation/service_requests/pages/resolved_service_requests_page.dart, test/widget_tests/presentation/profile/edit_information_page_test.dart
=> fix: edit nickname page

lib/domain/core/value_objects/app_enums.dart, lib/presentation/service_requests/pages/pin_reset_requests_page.dart, lib/presentation/service_requests/pages/red_flags_page.dart, lib/presentation/service_requests/pages/service_requests_page.dart, test/widget_tests/presentation/service_requests/service_requests_page_test.dart
- add request type to query variables
=> fix: fix red flag query

lib/domain/core/value_objects/app_strings.dart, lib/presentation/onboarding/patient/add_new_patient_page.dart
=> fix: register patient button width

lib/domain/core/value_objects/app_strings.dart, lib/presentation/profile/faqs/pages/profile_faqs_page.dart, lib/presentation/profile/faqs/widgets/faq_item.dart, test/widget_tests/presentation/profile/FAQs/profile_faqs_page_test.dart
=> fix: faq UI fixes

lib/application/core/graphql/queries.dart, lib/application/redux/actions/service_requests/fetch_service_request_count_action.dart, lib/application/redux/actions/service_requests/fetch_service_requests_action.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/engagement/home/widgets/action_card.dart, lib/presentation/service_requests/pages/pin_reset_requests_page.dart, lib/presentation/service_requests/pages/red_flags_page.dart, lib/presentation/service_requests/pages/resolved_service_requests_page.dart, lib/presentation/service_requests/pages/service_requests_page.dart, lib/presentation/service_requests/widgets/service_request_action_card.dart, test/widget_tests/presentation/engagement/home/widgets/action_card_test.dart, test/widget_tests/presentation/service_requests/pin_reset_requests_page_test.dart, test/widget_tests/presentation/service_requests/red_flags_page_test.dart, test/widget_tests/presentation/service_requests/service_requests_page_test.dart
=> feat: pin reset requests implementation

lib/domain/core/value_objects/app_strings.dart, lib/domain/core/value_objects/app_widget_keys.dart, lib/presentation/communities/channel_page.dart, lib/presentation/community/group_info/pages/group_info_page.dart, lib/presentation/community/group_info/widgets/member_list_actions_dialog.dart, lib/presentation/create_group/invite_members/invite_members_page.dart, test/widget_tests/presentation/community/member_list_actions_dialog_test.dart
- fix group name not showing
- add ban user button and fix UI
=> feat: add ban user to user options

lib/presentation/client_details/pages/search_client_page.dart
=> refactor: search client page

lib/application/redux/actions/flags/app_flags.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/client_details/pages/search_client_page.dart, lib/presentation/client_details/pages/search_staff_member_page.dart, lib/presentation/client_details/widgets/search_client_item.dart, lib/presentation/router/route_generator.dart, lib/presentation/router/routes.dart, lib/presentation/search/pages/search_page.dart, test/widget_tests/presentation/client_details/search_client_page_test.dart, test/widget_tests/presentation/client_details/search_staff_member_page_test.dart, test/widget_tests/presentation/search/search_page_test.dart
=> feat: search staff member

lib/application/core/graphql/queries.dart, lib/application/redux/actions/search_users/search_client_action.dart, lib/domain/core/entities/search_user/search_user_response.dart, lib/domain/core/entities/search_user/search_user_response.freezed.dart, lib/domain/core/entities/search_user/search_user_response.g.dart, lib/domain/core/entities/search_user/searched_clients.dart, lib/domain/core/entities/search_user/searched_clients.freezed.dart, lib/domain/core/entities/search_user/searched_clients.g.dart, lib/presentation/client_details/pages/search_client_page.dart, test/mocks/mocks.dart, test/unit_tests/application/redux/actions/search_clients/search_client_action_test.dart, test/widget_tests/application/core/services/custom_client_test.mocks.dart, test/widget_tests/presentation/client_details/search_client_page_test.dart
=> refactor: clients search

lib/presentation/core/app_bar/app_bar_back_button.dart
=> refactor: app bar

lib/application/core/graphql/queries.dart
=> fix: search client

lib/application/core/theme/app_themes.dart, lib/application/redux/actions/complete_onboarding_tour.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/core/auth_manager.dart, lib/presentation/core/widgets/error_dialog.dart, test/unit_tests/application/redux/actions/onboarding/complete_onboarding_tour_test.dart
=> feat: default error dialog

lib/application/core/graphql/queries.dart, lib/domain/core/entities/community_members/member.dart, lib/domain/core/entities/community_members/member.freezed.dart, lib/domain/core/entities/community_members/member.g.dart, lib/presentation/community/group_info/pages/group_info_page.dart, lib/presentation/create_group/invite_members/invite_members_page.dart, test/mocks/mocks.dart, test/widget_tests/presentation/create_group/invite_members_page_test.dart
=> refactor: list members

lib/domain/core/value_objects/app_strings.dart, lib/presentation/engagement/home/pages/home_page.dart, lib/presentation/onboarding/patient/add_new_client_page.dart, lib/presentation/onboarding/patient/widgets/patient_details_text_form_field.dart, lib/presentation/onboarding/staff/add_new_staff_page.dart, lib/presentation/router/route_generator.dart, test/unit_tests/presentation/router/route_generator_test.dart, test/widget_tests/presentation/client_details/search_client_page_test.dart, test/widget_tests/presentation/engagement/home/pages/home_page_test.dart, test/widget_tests/presentation/onboarding/patient/add_new_client_page_test.dart
=> fix: register client page fixes

lib/application/core/graphql/queries.dart, lib/application/core/services/utils.dart, lib/domain/core/entities/service_requests/service_request_content.dart, lib/domain/core/entities/service_requests/service_request_content.freezed.dart, lib/domain/core/entities/service_requests/service_request_content.g.dart, lib/presentation/service_requests/pages/red_flags_page.dart, lib/presentation/service_requests/widgets/red_flag_list_item.dart, test/mocks/mocks.dart
- add time stamps to service requests
=> chore: add time stamp to red flags service requests

lib/application/core/graphql/queries.dart, lib/application/redux/actions/search_users/search_staff_member_action.dart, lib/domain/core/entities/search_user/search_user_response.dart, lib/domain/core/entities/search_user/search_user_response.freezed.dart, lib/domain/core/entities/search_user/search_user_response.g.dart, lib/domain/core/entities/search_user/searched_staff_members.dart, lib/domain/core/entities/search_user/searched_staff_members.freezed.dart, lib/domain/core/entities/search_user/searched_staff_members.g.dart, lib/presentation/client_details/pages/search_staff_member_page.dart, test/mocks/mocks.dart, test/unit_tests/application/redux/actions/search_clients/search_staff_members_action_test.dart, test/widget_tests/presentation/client_details/search_staff_member_page_test.dart
=> chore: search staff member

lib/application/core/graphql/mutations.dart, lib/application/core/graphql/queries.dart, lib/application/redux/actions/search_users/invite_client_action.dart, lib/application/redux/actions/search_users/invite_staff_action.dart, lib/domain/core/entities/search_user/search_user_response.dart, lib/domain/core/entities/search_user/search_user_response.freezed.dart, lib/domain/core/entities/search_user/user_data.dart, lib/domain/core/entities/search_user/user_data.freezed.dart, lib/domain/core/entities/search_user/user_data.g.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/client_details/pages/search_client_page.dart, lib/presentation/client_details/pages/search_staff_member_page.dart, lib/presentation/client_details/widgets/search_user_item.dart, lib/presentation/router/route_generator.dart, lib/presentation/search/pages/search_page.dart, lib/presentation/search/pages/search_page_detail_view.dart, lib/presentation/search/widgets/client_search_widget.dart, lib/presentation/search/widgets/search_details_information_widget.dart, lib/presentation/search/widgets/staff_search_widget.dart, test/mocks/mocks.dart, test/unit_tests/application/redux/actions/search_clients/invite_clients_action_test.dart, test/unit_tests/application/redux/actions/search_clients/invite_staff_action_test.dart, test/unit_tests/presentation/router/route_generator_test.dart, test/widget_tests/application/core/services/custom_client_test.mocks.dart, test/widget_tests/presentation/search/search_page_detail_view_test.dart, test/widget_tests/presentation/search/search_user_item_test.dart
- invite clients and staff to mycarehub
=> chore: implement invite for clients and staff to mycarehub

.circleci/config.yml, android/app/build.gradle
- upgrade CircleCI image to cimg/android:2022.03.1-ndk
- set ndkVersion to "22.1.7171670" in the new CI image
=> feat: fix android deployment

lib/application/core/services/utils.dart, lib/application/redux/actions/core/phone_login_action.dart, lib/application/redux/actions/create_pin_action.dart, lib/application/redux/actions/onboarding/verify_otp_action.dart, lib/application/redux/actions/security_questions/record_security_question_responses_action.dart, lib/application/redux/view_models/onboarding/verify_phone_view_model.dart, lib/presentation/onboarding/create_pin/pages/create_new_pin_page.dart, lib/presentation/onboarding/set_nickname/set_nickname_page.dart, lib/presentation/onboarding/terms/terms_and_conditions_page.dart, lib/presentation/onboarding/verify_phone/widgets/verify_otp_widget.dart
- read phone number from onboarding state instead of the user state
- implement navigation based on the current onboarding state
- fix app theming issues
=> fix: new user onboarding

lib/application/core/graphql/mutations.dart, lib/application/core/theme/app_themes.dart, lib/application/redux/actions/flags/app_flags.dart, lib/application/redux/actions/search_users/assign_roles_action.dart, lib/application/redux/actions/search_users/invite_client_action.dart, lib/domain/core/value_objects/app_strings.dart, lib/domain/core/value_objects/app_widget_keys.dart, lib/presentation/search/widgets/client_search_widget.dart, lib/presentation/search/widgets/staff_search_widget.dart, test/mocks/mocks.dart, test/unit_tests/application/redux/actions/search_clients/assign_roles_action_test.dart, test/widget_tests/presentation/search/search_page_detail_view_test.dart
- implement assigning of roles to staff members
=> feat: implement assign roles to staff members

lib/application/core/graphql/mutations.dart, lib/application/redux/actions/communities/remove_from_group_action.dart, lib/application/redux/actions/flags/app_flags.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/community/group_info/pages/group_info_page.dart, lib/presentation/community/group_info/widgets/group_member_item.dart, lib/presentation/community/group_info/widgets/member_list_actions_dialog.dart, test/mocks/mocks.dart, test/widget_tests/application/redux/actions/communities/remove_from_group_action_test.dart, test/widget_tests/presentation/community/member_list_actions_dialog_test.dart
- implement remove user from group
=> feat: implement remove user from group

lib/application/core/services/utils.dart, lib/application/redux/actions/create_pin_action.dart, lib/application/redux/actions/onboarding/verify_otp_action.dart, lib/application/redux/actions/set_nick_name_action.dart, lib/domain/core/value_objects/app_strings.dart, lib/domain/core/value_objects/error_tags.dart, lib/presentation/onboarding/create_pin/pages/create_new_pin_page.dart, test/widget_tests/presentation/onboarding/create_pin/create_new_pin_page_test.dart, test/widget_tests/presentation/onboarding/create_pin/create_pin_action_test.dart
- make it flexible to allow pin resets and changes
=> refactor: create PIN page

lib/application/core/graphql/queries.dart, lib/domain/core/entities/service_requests/service_request_content.dart, lib/domain/core/entities/service_requests/service_request_content.freezed.dart, lib/domain/core/entities/service_requests/service_request_content.g.dart, lib/presentation/service_requests/pages/resolved_service_requests_page.dart, lib/presentation/service_requests/widgets/red_flag_list_item.dart, test/mocks/mocks.dart
- add resolvedByName in service request payload
=> fix: resolved service request page

lib/application/redux/actions/user_state_actions/check_token_action.dart
- implement resume on home page
=> refactor: on resume navigation

lib/domain/core/value_objects/app_strings.dart, lib/presentation/search/widgets/client_search_widget.dart, lib/presentation/search/widgets/staff_search_widget.dart
=> chore: fix search detail view

lib/application/redux/actions/register_client/register_client_action.dart, lib/application/redux/actions/register_staff/register_staff_action.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/onboarding/patient/register_staff_form_manager.dart, lib/presentation/onboarding/patient/validator_mixin.dart, lib/presentation/onboarding/staff/add_new_staff_page.dart, pubspec.lock, pubspec.yaml
- Fix phone number validation for different phone numbers
=> fix: register staff page

lib/application/core/graphql/queries.dart, lib/domain/core/entities/community_members/group_member.dart, lib/domain/core/entities/community_members/group_member.freezed.dart, lib/domain/core/entities/community_members/group_member.g.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/community/group_info/pages/group_info_page.dart, lib/presentation/community/group_info/widgets/group_member_item.dart, test/widget_tests/application/core/services/custom_client_test.mocks.dart, test/widget_tests/presentation/community/group_info_page_test.dart, test/widget_tests/presentation/community/group_member_item_test.dart
=> feat: show moderators

lib/domain/core/value_objects/app_strings.dart, lib/presentation/flagged_messages/pages/flagged_messages_page.dart, lib/presentation/flagged_messages/widgets/flagged_messages_list_item.dart, lib/presentation/router/route_generator.dart, lib/presentation/router/routes.dart, test/unit_tests/presentation/router/route_generator_test.dart, test/widget_tests/presentation/flagged_messages/flagged_messages_page_test.dart
=> feat: flagged messages

lib/application/core/theme/app_themes.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/community/group_info/pages/group_info_page.dart, lib/presentation/create_group/create_group.dart, lib/presentation/create_group/invite_members/invite_members_page.dart, lib/presentation/service_requests/pages/pin_reset_requests_page.dart, lib/presentation/service_requests/widgets/pin_reset_request_widget.dart
=> feat: flagged messages button

lib/application/core/graphql/mutations.dart, lib/application/redux/actions/service_requests/resolve_pin_request_action.dart, lib/infrastructure/endpoints.dart, lib/presentation/engagement/home/pages/home_page.dart, pubspec.lock, pubspec.yaml, test/mocks/mocks.dart
- fix profile avatar initials
- fix graphql endpoint
- fix service request queries
=> feat: fix service request issues

lib/application/core/graphql/mutations.dart, lib/application/redux/actions/search_users/assign_roles_action.dart, test/mocks/mocks.dart, test/unit_tests/application/redux/actions/search_clients/assign_roles_action_test.dart, test/widget_tests/presentation/client_details/staff_search_widget_test.dart
- fix assigning and revoking of roles
=> chore: fix assign revoke roles

lib/presentation/onboarding/patient/add_new_client_page.dart, lib/presentation/onboarding/patient/widgets/patient_details_text_form_field.dart, test/widget_tests/presentation/onboarding/patient/add_new_client_page_test.dart
=> refactor: add new client page

lib/application/core/services/utils.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/router/route_generator.dart, lib/presentation/router/routes.dart, lib/presentation/service_requests/pages/red_flag_actions_page.dart, lib/presentation/service_requests/pages/screening_tools_assessment_page.dart, lib/presentation/service_requests/widgets/assement_list_item.dart, lib/presentation/service_requests/widgets/assessment_card.dart, lib/presentation/service_requests/widgets/assessment_widget.dart, lib/presentation/service_requests/widgets/reach_out_widget.dart, test/unit_tests/presentation/router/route_generator_test.dart, test/widget_tests/presentation/service_requests/screening_tools_assessment_page_test.dart
=> feat: screening tools assessment

lib/presentation/core/app_bar/custom_app_bar.dart
- implement text wrapping if title is long
=> refactor: app bar title

lib/domain/core/value_objects/app_strings.dart, lib/presentation/service_requests/pages/screening_tools_assessment_page.dart
=> refactor: rename title

lib/presentation/service_requests/pages/service_requests_page.dart, test/widget_tests/presentation/service_requests/service_requests_page_test.dart
=> feat: refresh service requests

lib/application/core/theme/app_themes.dart, lib/presentation/community/group_info/pages/group_info_page.dart, lib/presentation/community/group_info/widgets/group_member_badge.dart, lib/presentation/community/group_info/widgets/group_member_item.dart, test/widget_tests/presentation/community/invited_groups/widgets/group_member_item_test.dart
=> feat: moderator badge ui

lib/presentation/onboarding/patient/add_new_client_page.dart, lib/presentation/onboarding/staff/add_new_staff_page.dart, test/widget_tests/presentation/onboarding/patient/add_new_client_page_test.dart, test/widget_tests/presentation/onboarding/staff/add_new_staff_page_test.dart
=> chore: restrict future dates

lib/domain/core/value_objects/app_strings.dart, lib/presentation/onboarding/patient/add_new_client_page.dart, lib/presentation/onboarding/staff/add_new_staff_page.dart
=> fix: invite text

lib/application/core/graphql/queries.dart, lib/application/core/services/helpers.dart, lib/application/redux/actions/flags/app_flags.dart, lib/application/redux/actions/search_users/fetch_staff_roles_action.dart, lib/application/redux/actions/search_users/invite_client_action.dart, lib/application/redux/actions/search_users/reactivate_client_action.dart, lib/application/redux/actions/search_users/search_client_action.dart, lib/application/redux/actions/search_users/search_staff_member_action.dart, lib/application/redux/actions/search_users/update_search_user_response_state_action.dart, lib/domain/core/entities/search_user/search_user_response.dart, lib/domain/core/entities/search_user/search_user_response.freezed.dart, lib/domain/core/entities/search_user/search_user_response.g.dart, lib/domain/core/value_objects/app_strings.dart, lib/infrastructure/endpoints.dart, lib/presentation/client_details/pages/search_client_page.dart, lib/presentation/client_details/pages/search_staff_member_page.dart, lib/presentation/client_details/widgets/search_user_item.dart, lib/presentation/search/widgets/client_search_widget.dart, pubspec.lock, pubspec.yaml, test/mocks/mocks.dart, test/unit_tests/application/redux/actions/search_clients/fetch_staff_roles_action_test.dart, test/unit_tests/application/redux/actions/search_clients/invite_clients_action_test.dart, test/widget_tests/application/core/services/custom_client_test.mocks.dart, test/widget_tests/presentation/client_details/search_client_page_test.dart, test/widget_tests/presentation/client_details/search_staff_member_page_test.dart, test/widget_tests/presentation/search/search_page_detail_view_test.dart
=> chore: handle deactivated users

lib/domain/core/entities/search_user/search_user_response.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/onboarding/staff/add_new_staff_page.dart
=> fix: register staff checkbox text

lib/domain/core/value_objects/app_strings.dart, lib/presentation/service_requests/pages/pin_reset_requests_page.dart, lib/presentation/service_requests/widgets/pin_reset_request_widget.dart, lib/presentation/service_requests/widgets/staff_pin_reset_request_widget.dart, test/widget_tests/presentation/service_requests/staff_pin_reset_requests_page_test.dart
* Fixed logout button height on resume with PIN page
* Changed accept pin request the to 'Approve'
* PIN request item spacing
=> fix: pin reset requests items spacing

lib/application/redux/actions/communities/accept_communities_invite_action.dart, lib/presentation/communities/invited_groups/pages/accept_group_invites_page.dart, test/widget_tests/presentation/community/invited_groups/pages/accept_group_invites_page_test.dart
- navigate to conversations when invite is accepted
=> chore: navigate to conversations on invite acceptance

lib/application/core/graphql/mutations.dart, lib/application/core/graphql/queries.dart, lib/application/redux/actions/flags/app_flags.dart, lib/application/redux/actions/service_requests/resolve_service_request_action.dart, lib/domain/core/value_objects/app_strings.dart, lib/domain/core/value_objects/app_widget_keys.dart, lib/presentation/service_requests/pages/red_flag_actions_page.dart, test/mocks/mocks.dart, test/widget_tests/presentation/service_requests/red_flag_actions_page_test.dart
=> chore: resolve red flag

lib/application/redux/actions/search_users/shared_health_diary_action.dart
=> fix: shared diary entries

lib/presentation/communities/flagged_messages/widgets/moderation_actions_dialog.dart
=> fix: loading indicator height

lib/application/redux/actions/resume_with_pin_action/resume_with_pin_action.dart, lib/presentation/resume_with_pin/resume_with_pin_page.dart, test/unit_tests/application/redux/actions/resume_with_pin/resume_with_pin_action_test.dart, test/widget_tests/presentation/resume_with_pin/resume_with_pin_page_test.dart
=> chore: log out users when pin is expired

lib/application/core/graphql/queries.dart, lib/application/core/services/utils.dart, lib/application/redux/actions/core/update_staff_profile_action.dart, lib/application/redux/actions/flags/app_flags.dart, lib/application/redux/actions/notifications/fetch_notifications_action.dart, lib/application/redux/view_models/notifications/notifications_view_model.dart, lib/domain/core/entities/core/staff_state.dart, lib/domain/core/entities/core/staff_state.freezed.dart, lib/domain/core/entities/core/staff_state.g.dart, lib/domain/core/entities/notification/notification_details.dart, lib/domain/core/entities/notification/notification_details.freezed.dart, lib/domain/core/entities/notification/notification_details.g.dart, lib/domain/core/entities/notification/notifications_data.dart, lib/domain/core/entities/notification/notifications_data.freezed.dart, lib/domain/core/entities/notification/notifications_data.g.dart, lib/domain/core/entities/notification/notifications_response.dart, lib/domain/core/entities/notification/notifications_response.freezed.dart, lib/domain/core/entities/notification/notifications_response.g.dart, lib/presentation/notifications/notifications_page.dart, lib/presentation/router/route_generator.dart, test/mocks/mocks.dart, test/unit_tests/application/redux/actions/notifications/fetch_notifications_action_test.dart, test/unit_tests/domain/core/entities/notification_details_test.dart, test/unit_tests/presentation/router/route_generator_test.dart, test/widget_tests/presentation/notifications/notifications_page_test.dart
=> chore: hook notifications api

lib/application/core/graphql/queries.dart, lib/application/redux/actions/search_users/assign_roles_action.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/search/widgets/staff_search_widget.dart, test/unit_tests/application/redux/actions/search_clients/assign_roles_action_test.dart, test/widget_tests/presentation/client_details/staff_search_widget_test.dart
=> fix: fix search

lib/application/redux/actions/service_requests/fetch_assessment_responses_by_tool_action.dart, lib/application/redux/actions/service_requests/fetch_available_facility_screening_tools_action.dart, lib/application/redux/actions/service_requests/resolve_screening_tool_service_request_action.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/service_requests/pages/assessment_card_answers_page.dart, lib/presentation/service_requests/pages/assessment_tools_responses_page.dart, lib/presentation/service_requests/pages/screening_tools_list_page.dart, test/widget_tests/presentation/service_requests/assessment_card_answers_page_test.dart, test/widget_tests/presentation/service_requests/assessment_tools_responses_page_test.dart, test/widget_tests/presentation/service_requests/screening_tools_list_page_test.dart
=> chore: screening tools zero state

lib/domain/core/value_objects/app_strings.dart, lib/domain/core/value_objects/app_widget_keys.dart, lib/presentation/router/route_generator.dart, lib/presentation/router/routes.dart, lib/presentation/service_requests/pages/resolved_service_requests_list_page.dart, lib/presentation/service_requests/pages/resolved_service_requests_page.dart, lib/presentation/service_requests/widgets/resolved_service_request_list_item.dart, test/unit_tests/presentation/router/route_generator_test.dart, test/widget_tests/presentation/profile/user_profile_page_test.dart, test/widget_tests/presentation/service_requests/resolved_service_requests_list_page_test.dart, test/widget_tests/presentation/service_requests/resolved_service_requests_page_test.dart
=> chore: refactor reesolved service requests

lib/presentation/core/app_bar/custom_app_bar.dart, lib/presentation/engagement/home/widgets/appbar_user.dart
=> fix: update app bar wrapping to ellipsis

lib/presentation/onboarding/login/pages/phone_login_page.dart
=> fix: nested scroll view on login page

lib/application/core/graphql/queries.dart
=> fix: flagged messages

lib/application/core/graphql/queries.dart, lib/application/core/services/utils.dart, lib/application/redux/actions/notifications/fetch_notifications_action.dart, lib/presentation/notifications/notifications_page.dart, test/mocks/mocks.dart
=> fix: notifications date format

lib/domain/core/entities/surveys/client_configuration_payload.dart, lib/domain/core/entities/surveys/client_configuration_payload.freezed.dart, lib/domain/core/entities/surveys/client_configuration_payload.g.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/surveys/pages/surveys_send_configuration_page.dart, lib/presentation/surveys/widgets/client_configuration_form_manager.dart, test/widget_tests/application/core/services/custom_client_test.mocks.dart, test/widget_tests/presentation/surveys/pages/surveys_send_configuration_page_test.dart
=> chore: add gender to client configuration

lib/application/redux/actions/set_nick_name_action.dart, lib/domain/core/value_objects/app_strings.dart, test/unit_tests/application/redux/actions/onboarding/set_nick_name_action_test.dart
=> fix: username taken

lib/presentation/surveys/pages/surveys_sender_list_page.dart, test/widget_tests/presentation/surveys/pages/surveys_sender_list_page_test.dart
=> refactor: send client surveys

lib/application/core/services/utils.dart, lib/presentation/profile/faqs/pages/content_details_page.dart, lib/presentation/profile/pages/user_profile_page.dart, pubspec.lock, pubspec.yaml, test/widget_tests/presentation/profile/FAQs/profile_faqs_page_test.dart
- refactor faq items to afyamojacore
=> chore: upgrade afyamojacore

lib/application/core/services/utils.dart, lib/presentation/core/pre_load_app.dart
- change inactive period for resume with pin work flow to 5 minutes
=> chore: change resume with pin timing

lib/domain/core/value_objects/app_strings.dart, lib/presentation/onboarding/security_questions/security_questions_page.dart
- ask for all security questions to be answered instead of one
=> fix: change prompt for security questions

lib/domain/core/value_objects/app_strings.dart, lib/presentation/core/widgets/animated_count.dart, lib/presentation/onboarding/login/pages/login_counter_page.dart, pubspec.lock, pubspec.yaml
- change resend otp counter text
- upgrade afyamoja_core
=> chore: reword resend otp prompt

lib/application/core/graphql/mutations.dart, lib/application/core/graphql/queries.dart, lib/application/redux/actions/flags/app_flags.dart, lib/application/redux/actions/search_users/invite_client_action.dart, lib/application/redux/actions/search_users/invite_staff_action.dart, lib/domain/core/entities/search_user/user_data.dart, lib/domain/core/entities/search_user/user_data.freezed.dart, lib/domain/core/entities/search_user/user_data.g.dart, lib/domain/core/value_objects/app_strings.dart, lib/domain/core/value_objects/app_widget_keys.dart, lib/presentation/search/widgets/active_client_actions.dart, lib/presentation/search/widgets/active_staff_actions.dart, lib/presentation/search/widgets/client_search_widget.dart, lib/presentation/search/widgets/inactive_user_actions.dart, lib/presentation/search/widgets/search_details_information_widget.dart, lib/presentation/search/widgets/staff_search_widget.dart, test/unit_tests/application/redux/actions/communities/update_group_info_action_test.mocks.dart, test/widget_tests/application/core/services/custom_client_test.mocks.dart, test/widget_tests/presentation/search/search_page_detail_view_test.dart
- update invite user query
- improve code flag naming
- refactor client and staff invites pages to add actions
- add names to client details when searching for them
- add tests
=> feat: reinvite clients and staff using alternative route

lib/application/redux/actions/security_questions/record_security_question_responses_action.dart
- fix recording of security questions
=> fix: fix recording of security questions

lib/application/core/graphql/queries.dart, lib/presentation/service_requests/widgets/red_flag_list_item.dart
- add date time stamp of creation on red flag items
=> feat: add createdAt label to red flags

ios/Podfile.lock, lib/domain/core/entities/create_group/age_range.dart, lib/domain/core/entities/create_group/age_range.freezed.dart, lib/domain/core/entities/create_group/age_range.g.dart, lib/domain/core/value_objects/app_strings.dart, lib/domain/core/value_objects/app_widget_keys.dart, lib/presentation/create_group/create_group_form_manager.dart, lib/presentation/onboarding/patient/widgets/patient_details_text_form_field.dart, lib/presentation/surveys/pages/surveys_send_configuration_page.dart, lib/presentation/surveys/widgets/client_configuration_form_manager.dart, lib/presentation/surveys/widgets/validator_mixin.dart, test/unit_tests/domain/core/entities/create_group/create_group_payload_test.dart, test/widget_tests/presentation/surveys/pages/surveys_send_configuration_page_test.dart
=> chore: send surveys UI update

lib/presentation/create_group/create_group.dart, lib/presentation/create_group/create_group_form_manager.dart, lib/presentation/onboarding/patient/validator_mixin.dart, test/widget_tests/presentation/create_group/create_group_test.dart
=> chore: remove age slider from create group

lib/presentation/profile/faqs/pages/profile_faqs_page.dart
=> fix: FAQs page scrolling

lib/presentation/service_requests/pages/red_flags_page.dart, lib/presentation/service_requests/widgets/service_requests_widget.dart, test/widget_tests/presentation/service_requests/red_flags_page_test.dart
- add refresh indicator to red flags page
=> chore: add refresh indicator to red flags page

lib/domain/core/value_objects/app_strings.dart, lib/presentation/onboarding/login/pages/phone_login_page.dart, lib/presentation/profile/pages/settings_page.dart, lib/presentation/profile/pages/user_profile_page.dart
=> feat: add copyright to login and profile pages

lib/application/core/graphql/queries.dart, lib/application/redux/actions/communities/fetch_group_members_action.dart, lib/application/redux/actions/communities/update_group_state_action.dart, lib/application/redux/states/groups_state.dart, lib/application/redux/states/groups_state.freezed.dart, lib/domain/community/entities/age_range.dart, lib/domain/community/entities/age_range.freezed.dart, lib/domain/community/entities/age_range.g.dart, lib/domain/community/entities/list_group_info_response.dart, lib/domain/community/entities/list_group_info_response.freezed.dart, lib/domain/community/entities/list_group_info_response.g.dart, lib/domain/core/entities/community_members/community.dart, lib/domain/core/entities/community_members/community.freezed.dart, lib/domain/core/entities/community_members/community.g.dart, lib/domain/core/entities/create_group/create_group_payload.dart, lib/domain/core/entities/surveys/client_configuration_payload.dart, lib/domain/core/value_objects/app_enums.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/communities/group_info/pages/group_info_page.dart, lib/presentation/communities/view_models/groups_view_model.dart, lib/presentation/create_group/create_group_form_manager.dart, lib/presentation/surveys/widgets/client_configuration_form_manager.dart, test/mocks/mocks.dart, test/unit_tests/core/entities/community_test.dart, test/unit_tests/domain/core/entities/create_group/create_group_payload_test.dart, test/widget_tests/application/core/services/custom_client_test.mocks.dart
=> feat: add more details to group info page

lib/domain/core/value_objects/app_strings.dart, lib/presentation/engagement/home/widgets/appbar_user.dart, lib/presentation/onboarding/patient/register_client_page.dart, lib/presentation/onboarding/staff/add_new_staff_page.dart, lib/presentation/search/widgets/active_client_actions.dart, lib/presentation/search/widgets/active_staff_actions.dart, test/widget_tests/presentation/client_details/staff_search_widget_test.dart
=> fix: app user icon color and invite to myCareHub

lib/domain/core/value_objects/app_strings.dart, lib/presentation/client_details/pages/search_staff_member_page.dart
=> feat: change hint text

lib/presentation/onboarding/login/pages/phone_login_page.dart
=> feat: fix login btn color

lib/application/core/graphql/mutations.dart, lib/application/redux/actions/service_requests/resolve_screening_tool_service_request_action.dart, lib/application/redux/actions/service_requests/resolve_service_request_action.dart, lib/domain/core/value_objects/app_strings.dart, lib/presentation/service_requests/pages/assessment_card_answers_page.dart, lib/presentation/service_requests/pages/red_flag_actions_page.dart, test/widget_tests/presentation/service_requests/assessment_card_answers_page_test.dart, test/widget_tests/presentation/service_requests/red_flag_actions_page_test.dart
=> feat: add action checkbokes to resolve service request action page

lib/presentation/profile/pages/facility_contacts_page.dart, test/widget_tests/presentation/profile/facility_contacts_page_test.dart, test/widget_tests/presentation/profile/user_profile_page_test.dart
=> chore: disable update contact for other staff

lib/presentation/onboarding/verify_phone/widgets/verify_otp_widget.dart
The otp field during phone number verification is autofilled
=> feat: sms autofill

lib/application/core/graphql/queries.dart, lib/application/core/theme/app_themes.dart, lib/application/redux/actions/service_requests/search_service_requests_action.dart, lib/domain/core/entities/service_requests/search_service_request_response.dart, lib/domain/core/entities/service_requests/search_service_request_response.freezed.dart, lib/domain/core/entities/service_requests/search_service_request_response.g.dart, lib/domain/core/value_objects/app_strings.dart, lib/domain/core/value_objects/app_widget_keys.dart, lib/presentation/onboarding/core/search_facilities_page.dart, lib/presentation/router/route_generator.dart, lib/presentation/service_requests/pages/assessment_tools_responses_page.dart, lib/presentation/service_requests/pages/pin_reset_requests_page.dart, lib/presentation/service_requests/pages/red_flags_page.dart, lib/presentation/service_requests/pages/staff_pin_reset_requests_page.dart, pubspec.lock, test/mocks/mocks.dart, test/unit_tests/application/redux/actions/service_requests/search_service_requests_action_test.dart, test/widget_tests/application/core/services/custom_client_test.mocks.dart, test/widget_tests/presentation/service_requests/pin_reset_requests_page_test.dart, test/widget_tests/presentation/service_requests/red_flags_page_test.dart, test/widget_tests/presentation/service_requests/staff_pin_reset_requests_page_test.dart
=> feat: service requests search field

ios/Podfile.lock, lib/application/core/graphql/queries.dart, lib/application/core/theme/app_themes.dart, lib/application/redux/actions/notifications/fetch_notifications_action.dart, lib/application/redux/actions/notifications/fetch_notifications_filters_action.dart, lib/application/redux/actions/notifications/update_notification_filter_state.dart, lib/application/redux/view_models/notifications/notifications_view_model.dart, lib/domain/core/entities/core/notification_filter_state.dart, lib/domain/core/entities/core/notification_filter_state.freezed.dart, lib/domain/core/entities/core/notification_filter_state.g.dart, lib/domain/core/entities/core/staff_state.dart, lib/domain/core/entities/core/staff_state.freezed.dart, lib/domain/core/entities/core/staff_state.g.dart, lib/domain/core/value_objects/app_strings.dart, lib/domain/core/value_objects/app_widget_keys.dart, lib/presentation/notifications/notifications_page.dart, lib/presentation/notifications/widgets/custom_chip_widget.dart, pubspec.yaml, test/mocks/mocks.dart, test/unit_tests/application/redux/actions/communities/check_user_is_moderator_action_test.mocks.dart, test/unit_tests/application/redux/actions/communities/check_user_is_owner_action_test.mocks.dart, test/unit_tests/application/redux/actions/communities/delete_group_action_test.mocks.dart, test/unit_tests/application/redux/actions/communities/update_group_info_action_test.mocks.dart, test/unit_tests/application/redux/actions/notifications/fetch_notification_filters_action_test.dart, test/unit_tests/application/redux/actions/notifications/notification_filter_state_test.dart, test/widget_tests/presentation/notifications/notifications_page_test.dart
- add notifications filtering
Signed-off-by: Byron Kimani <byronkimani@Byrons-MacBook-Pro.local>
=> feat: add notifications filtering
